// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommandExecution {
    #[prost(message, optional, tag = "1")]
    pub details: ::core::option::Option<CommandExecutionDetails>,
    #[prost(message, optional, tag = "20")]
    pub inline_environment_metadata: ::core::option::Option<
        InlineCommandExecutionEnvironmentMetadata,
    >,
    #[prost(oneof = "command_execution::Status", tags = "2, 3, 4, 5, 7, 8")]
    pub status: ::core::option::Option<command_execution::Status>,
}
/// Nested message and enum types in `CommandExecution`.
pub mod command_execution {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Success {}
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Failure {}
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct WorkerFailure {}
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Timeout {
        #[prost(message, optional, tag = "1")]
        pub duration: ::core::option::Option<::prost_types::Duration>,
    }
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Error {
        #[prost(string, tag = "1")]
        pub stage: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub error: ::prost::alloc::string::String,
    }
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Cancelled {}
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Status {
        #[prost(message, tag = "2")]
        Success(Success),
        #[prost(message, tag = "3")]
        Failure(Failure),
        #[prost(message, tag = "4")]
        Timeout(Timeout),
        #[prost(message, tag = "5")]
        Error(Error),
        #[prost(message, tag = "7")]
        Cancelled(Cancelled),
        #[prost(message, tag = "8")]
        WorkerFailure(WorkerFailure),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommandExecutionKind {
    #[prost(oneof = "command_execution_kind::Command", tags = "1, 2, 3, 4, 5")]
    pub command: ::core::option::Option<command_execution_kind::Command>,
}
/// Nested message and enum types in `CommandExecutionKind`.
pub mod command_execution_kind {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Command {
        #[prost(message, tag = "1")]
        LocalCommand(super::LocalCommand),
        #[prost(message, tag = "2")]
        RemoteCommand(super::RemoteCommand),
        #[prost(message, tag = "3")]
        OmittedLocalCommand(super::OmittedLocalCommand),
        #[prost(message, tag = "4")]
        WorkerInitCommand(super::WorkerInitCommand),
        #[prost(message, tag = "5")]
        WorkerCommand(super::WorkerCommand),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InlineCommandExecutionEnvironmentMetadata {
    #[prost(uint64, optional, tag = "1")]
    pub sandcastle_instance_id: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommandExecutionDetails {
    #[prost(sint32, optional, tag = "4")]
    pub signed_exit_code: ::core::option::Option<i32>,
    #[prost(string, tag = "2")]
    pub cmd_stdout: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub cmd_stderr: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub command_kind: ::core::option::Option<CommandExecutionKind>,
    #[prost(message, optional, tag = "13")]
    pub metadata: ::core::option::Option<CommandExecutionMetadata>,
    #[prost(string, optional, tag = "14")]
    pub additional_message: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LocalCommand {
    #[prost(string, repeated, tag = "1")]
    pub argv: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "2")]
    pub env: ::prost::alloc::vec::Vec<EnvironmentEntry>,
    #[prost(string, tag = "3")]
    pub action_digest: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkerInitCommand {
    #[prost(string, repeated, tag = "1")]
    pub argv: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "2")]
    pub env: ::prost::alloc::vec::Vec<EnvironmentEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkerCommand {
    #[prost(string, repeated, tag = "1")]
    pub argv: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "2")]
    pub env: ::prost::alloc::vec::Vec<EnvironmentEntry>,
    #[prost(string, tag = "3")]
    pub action_digest: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub fallback_exe: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OmittedLocalCommand {
    #[prost(string, tag = "1")]
    pub action_digest: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoteCommand {
    #[prost(string, tag = "1")]
    pub action_digest: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub cache_hit: bool,
    #[prost(message, optional, tag = "3")]
    pub queue_time: ::core::option::Option<::prost_types::Duration>,
    #[prost(message, optional, tag = "4")]
    pub details: ::core::option::Option<RemoteCommandDetails>,
    #[prost(enumeration = "CacheHitType", tag = "5")]
    pub cache_hit_type: i32,
    #[prost(string, optional, tag = "6")]
    pub remote_dep_file_key: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "7")]
    pub materialized_inputs_for_failed: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
    #[prost(string, repeated, tag = "8")]
    pub materialized_outputs_for_failed_actions: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CommandExecutionMetadata {
    #[prost(message, optional, tag = "1")]
    pub wall_time: ::core::option::Option<::prost_types::Duration>,
    #[prost(message, optional, tag = "2")]
    pub execution_time: ::core::option::Option<::prost_types::Duration>,
    #[prost(message, optional, tag = "3")]
    pub start_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "4")]
    pub input_materialization_duration: ::core::option::Option<::prost_types::Duration>,
    #[prost(message, optional, tag = "5")]
    pub execution_stats: ::core::option::Option<CommandExecutionStats>,
    #[prost(message, optional, tag = "6")]
    pub hashing_duration: ::core::option::Option<::prost_types::Duration>,
    #[prost(uint64, tag = "7")]
    pub hashed_artifacts_count: u64,
    #[prost(message, optional, tag = "8")]
    pub queue_duration: ::core::option::Option<::prost_types::Duration>,
    #[prost(message, optional, tag = "10")]
    pub suspend_duration: ::core::option::Option<::prost_types::Duration>,
    #[prost(uint64, optional, tag = "11")]
    pub suspend_count: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnvironmentEntry {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoteCommandDetails {
    #[prost(string, optional, tag = "1")]
    pub session_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "2")]
    pub use_case: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub platform: ::core::option::Option<RePlatform>,
    #[prost(bool, tag = "4")]
    pub persistent_worker: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CommandExecutionStats {
    #[prost(uint64, optional, tag = "1")]
    pub cpu_instructions_user: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "2")]
    pub cpu_instructions_kernel: ::core::option::Option<u64>,
    #[prost(message, optional, tag = "3")]
    pub userspace_events: ::core::option::Option<CpuCounter>,
    #[prost(message, optional, tag = "4")]
    pub kernel_events: ::core::option::Option<CpuCounter>,
    #[prost(uint64, optional, tag = "5")]
    pub memory_peak: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RePlatform {
    #[prost(message, repeated, tag = "1")]
    pub properties: ::prost::alloc::vec::Vec<re_platform::Property>,
}
/// Nested message and enum types in `RePlatform`.
pub mod re_platform {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Property {
        #[prost(string, tag = "1")]
        pub name: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub value: ::prost::alloc::string::String,
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CpuCounter {
    #[prost(uint64, tag = "1")]
    pub count: u64,
    #[prost(uint64, tag = "2")]
    pub time_enabled: u64,
    #[prost(uint64, tag = "3")]
    pub time_running: u64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CacheHitType {
    ActionCache = 0,
    RemoteDepFileCache = 1,
    Executed = 2,
}
impl CacheHitType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ActionCache => "ACTION_CACHE",
            Self::RemoteDepFileCache => "REMOTE_DEP_FILE_CACHE",
            Self::Executed => "EXECUTED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ACTION_CACHE" => Some(Self::ActionCache),
            "REMOTE_DEP_FILE_CACHE" => Some(Self::RemoteDepFileCache),
            "EXECUTED" => Some(Self::Executed),
            _ => None,
        }
    }
}
