import { readFileSync } from "node:fs";
import { cloudflareTest } from "@cloudflare/vitest-pool-workers";
import { defineConfig } from "vitest/config";
import { WORKERD_TEST_TIMEOUT_MS } from "./src/test-bounds.ts";

export default defineConfig({
  plugins: [
    cloudflareTest({
      wrangler: { configPath: "./wrangler.authenticated.test.toml" },
      // Fresh native CLI/custodian output, generated by npm run norm:vector.
      miniflare: { bindings: {
        NORM_IMPACT_VECTOR: readFileSync(new URL("../../../target/norm-impact-vector.json", import.meta.url), "utf8"),
        NORM_PUBLICATION_VECTOR: readFileSync(new URL("../../../target/norm-publication-vector.json", import.meta.url), "utf8"),
        NORM_PORTABLE_VECTOR: readFileSync(new URL("../../../target/norm-portable-vector.json", import.meta.url), "utf8"),
      } },
    }),
  ],
  test: {
    include: [
      "src/authenticated-host.integration.test.ts",
      "src/norm-impact.integration.test.ts",
      "src/private-home-objects.integration.test.ts",
    ],
    // Bounds a hang, not the machine's load. See `src/test-bounds.ts`.
    testTimeout: WORKERD_TEST_TIMEOUT_MS,
    // A failed assertion must not leak a provider stub or suppressed console
    // into the next case. Match the ordinary host suite's global isolation.
    unstubGlobals: true,
    restoreMocks: true,
  },
});
