load ../managed-source-flows.maude
search [1] in WHIPPLESCRIPT-MANAGED-SOURCE-FLOWS : crossing(true, false, true, false, true, false) =>! decision(true, true) .
search [1] in WHIPPLESCRIPT-MANAGED-SOURCE-FLOWS : crossing(true, false, false, false, true, false) =>! decision(true, true) .
search [1] in WHIPPLESCRIPT-MANAGED-SOURCE-FLOWS-LOST : crossing(true, false, false, false, true, false) =>! decision(true, true) .
search [1] in WHIPPLESCRIPT-MANAGED-SOURCE-FLOWS : crossing(true, false, false, true, false, true) =>! decision(true, true) .
search [1] in WHIPPLESCRIPT-MANAGED-SOURCE-FLOWS-LOST : crossing(true, false, false, true, false, true) =>! decision(true, true) .
search [1] in WHIPPLESCRIPT-MANAGED-SOURCE-FLOWS : crossing(false, true, false, true, false, true) =>! decision(true, true) .
search [1] in WHIPPLESCRIPT-MANAGED-SOURCE-FLOWS : crossing(false, true, false, true, false, false) =>! decision(true, true) .
search [1] in WHIPPLESCRIPT-MANAGED-SOURCE-FLOWS : crossing(true, true, true, true, true, true) =>! decision(true, true) .
search [1] in WHIPPLESCRIPT-MANAGED-SOURCE-FLOWS : crossing(true, false, true and false, false, true, false) =>! decision(true, true) .
quit
