//! Native stores generated by the exact runtime pinned before the MTARGET repair.
//! SQL dumps retain the old schema as well as the rows; the owning adapters must
//! open/migrate them normally. See fixtures/mtarget-v1.0.1/README.md for provenance.
#![cfg(feature = "native")]

#[path = "support/receipt_fixture.rs"]
mod receipt_fixture;
use receipt_fixture::{expected, Fixture};
use whipplescript_store::workstreams::{
    fork_at_cut_and_admit, ExactForkDestination, StreamStatus, Workstreams,
};

#[test]
fn old_home_and_lost_fork_response_replay_the_original_evidence() {
    let fixture = Fixture::load("fork");
    for at in ["after-upgrade", "after-restart"] {
        let (mut streams, mut vcs) = fixture.open();
        let home = serde_json::to_value(
            streams
                .home_receipt("chat")
                .expect("legacy receipt operation succeeds"),
        )
        .expect("legacy receipt operation succeeds");
        assert_eq!(home, expected("fork", "source-home.json"));
        let fork = fork_at_cut_and_admit(
            &mut streams,
            &mut vcs,
            "parent",
            "chat-1",
            "child",
            "chat-child",
            None,
            ExactForkDestination::Workstream("ws"),
            at,
        )
        .expect("legacy receipt operation succeeds")
        .receipt();
        assert_eq!(
            serde_json::to_value(fork).expect("legacy receipt operation succeeds"),
            expected("fork", "fork.json")
        );
        assert_eq!(
            vcs.read("chat-child", "state.txt")
                .expect("legacy receipt operation succeeds")
                .as_deref(),
            Some("point")
        );
        assert_eq!(
            vcs.get_branch("chat-child")
                .expect("legacy receipt operation succeeds")
                .expect("legacy receipt operation succeeds")
                .branch_point_cut_id
                .as_deref(),
            Some("chat-1")
        );
    }
}

#[test]
fn old_archived_receipt_replays_without_rewriting_its_handle() {
    let fixture = Fixture::load("archived");
    for _ in 0..2 {
        let (streams, vcs) = fixture.open();
        let row = streams
            .get_stream("ws")
            .expect("legacy receipt operation succeeds")
            .expect("legacy receipt operation succeeds");
        assert_eq!(row.status, StreamStatus::Archived);
        assert_eq!(
            serde_json::to_value(
                row.boundary_receipt("workspace")
                    .expect("legacy receipt operation succeeds")
            )
            .expect("legacy receipt operation succeeds"),
            expected("archived", "boundary.json")
        );
        assert_eq!(
            vcs.branch_head_reservation("line")
                .expect("legacy receipt operation succeeds"),
            None
        );
    }
}

#[test]
fn old_landed_boundary_recovers_without_rekeying_the_accepted_fact() {
    let fixture = Fixture::load("landed");
    for _ in 0..2 {
        let (streams, vcs) = fixture.open();
        assert_eq!(
            streams
                .get_stream("ws")
                .expect("legacy receipt operation succeeds")
                .expect("legacy receipt operation succeeds")
                .status,
            StreamStatus::BoundaryReserved
        );
        let (position, handle) = vcs
            .boundary_ref_evidence("line", Some("main-1"), "main-2")
            .expect("legacy receipt operation succeeds")
            .expect("legacy receipt operation succeeds");
        assert_eq!(
            serde_json::json!({ "ref_position": position, "ref_receipt_handle": handle }),
            expected("landed", "accepted-ref.json")
        );
        assert_eq!(
            vcs.get_branch("main")
                .expect("legacy receipt operation succeeds")
                .expect("legacy receipt operation succeeds")
                .head_cut_id
                .as_deref(),
            Some("main-2")
        );
        assert_eq!(
            vcs.branch_head_reservation("line")
                .expect("legacy receipt operation succeeds")
                .as_deref(),
            Some("reservation")
        );
    }
}
